### ISSUE TITLE
Manually collapse sidebars

### ISSUE THREAD

**Issue by abhisekp** [gitterHQ/gitter#913] opened 2015-10-14 09:33 UTC
The sidebars to the left and right i.e. channel list and activity section respectively should've some manually collapsing feature to make the chat area more spacious to chat in.

The sidebars take a lot of space. The right activity sidebar auto collapse on small browser width but the left channel list sidebar doesn't. 

It would be really if I could even collapse them manually even if browser size is large.

**Comment by MadLittleMods** [comment] 2015-10-14 09:34
Duplicate of https://github.com/gitterHQ/gitter/issues/296. Move dicussion there :grinning:

**Closed by MadLittleMods** 2015-10-14 09:34 UTC
