### ISSUE TITLE
Gitter for Windows Desktop - Rendering issue

### ISSUE THREAD

**Issue by raisedadead** [gitterHQ/gitter#1236] opened 2016-05-01 11:33 UTC
System :

`Windows NT 10.0; WOW64`

![image](https://cloud.githubusercontent.com/assets/1884376/14941530/087ea7e0-0fbd-11e6-8572-011bbf636fe9.png)

Please check the above screenshot for the issue, I have the Dev console open as well for reference.
Let me know if you guys need any assistance with this.

Thanks.

**Comment by raisedadead** [comment] 2016-05-01 13:21
On a side note this is related to #1235

**Comment by MadLittleMods** [comment] 2016-05-01 18:14
Duplicate of https://github.com/gitterHQ/gitter/issues/1235 and https://github.com/gitterHQ/change/issues/38

**Closed by MadLittleMods** 2016-05-01 18:14 UTC
