### ISSUE TITLE
Search under Explore is missing results

### ISSUE THREAD

**Issue by raine** [gitterHQ/gitter#971] opened 2015-11-14 16:25 UTC
I searched for "ramda" and it should find at least [ramda/ramda](https://gitter.im/ramda/ramda), but doesn't.

<img width="1020" alt="screen shot 2015-11-14 at 18 22 49" src="https://cloud.githubusercontent.com/assets/11027/11164551/cf3a7ac6-8afc-11e5-9a5b-63434fc434da.png">

**Comment by MadLittleMods** [comment] 2015-12-16 13:56
Duplicate of https://github.com/gitterHQ/gitter/issues/582

**Closed by MadLittleMods** 2015-12-16 13:56 UTC
Labels: enhancement
