### ISSUE TITLE
Italicizing regex issue

### ISSUE THREAD

**Issue by a11smiles** [gitterHQ/gitter#1078] opened 2016-01-19 22:09 UTC
When there are more than one italicized words/phrases with regular text in the middle  

Ex: `The _brown_ fox jumps over the _red_ fence.`

Gitter results in:

The _brown__ _fox jumps over the _red_ fence.

**Comment by MadLittleMods** [comment] 2016-01-20 17:34
Duplicate of https://github.com/gitterHQ/marked/issues/4

**Closed by MadLittleMods** 2016-01-20 17:34 UTC
