### ISSUE TITLE
Channel Names prefaced with Org name

### ISSUE THREAD

**Issue by karlcarstensen** [gitterHQ/gitter#643] opened 2015-03-31 22:24 UTC
Within an organization, some of my channel names are prefaced with the organization name like: org-name/channel-name while others are just listed as the channel name without the org name.

**Comment by malditogeek** [comment] 2015-04-01 10:00
@karlcarstensen we truncate the org name in the list if the the combination of `org/channel` is too long and just display the channel (or repo) name, is that the case?

**Comment by karlcarstensen** [comment] 2015-04-01 20:29
Yes, now that you've called that out, it looks like that might be the case. I guess I would say it's a confusing user experience then, because that wasn't immediately apparent to anyone in our org.

We initially noticed it when scanning the list looking for a certain name, it makes it more difficult to find things because your eyes need to zig-zag down the page.

**Comment by mydigitalself** [comment] 2015-04-09 14:20
Going to close this as it's by design. Future UI improvements may include a solve on this, but for the sake of sanity of our issue list, closing.

**Closed by mydigitalself** 2015-04-09 14:20 UTC
