### ISSUE TITLE
Gitter IRC Bridge emits invalid string on /NAMES

### ISSUE THREAD

**Issue by Fryguy** [gitterHQ/gitter#1260] opened 2016-05-19 22:01 UTC
I am writing a gitter bot that is using the IRC bridge and the `cinch` gem.  When cinch connects to IRC, it issues a `/NAMES` command and then parses the results, however the result for the "Gitter Bot" is malformed.

A normal user looks like:

```
:irc.gitter.im 352 miq-bot #manageiq/manageiq Fryguy irc.gitter.im irc.gitter.im Fryguy H :0 Jason Frey
```

The Gitter Bot looks like:

```
:irc.gitter.im 352 miq-bot #manageiq/manageiq gitter :irc.gitter.im irc.gitter.im gitter H :0 Gitter Bot
```

Notice the extra `:` in the middle of the string before `irc.gitter.im`. I originally opened this issue on cinch at https://github.com/cinchrb/cinch/issues/226 and you can see more information there.

**Comment by Fryguy** [comment] 2016-05-19 22:11
This may actually be an invalid RPL_WHOREPLY from a `/WHO` command (I don't understand IRC commands 100%, so I'm just following the log and learning as I go along 😄 )

**Comment by MadLittleMods** [comment] 2016-05-19 22:56
Duplicate of https://github.com/gitterHQ/irc-bridge/issues/53

**Closed by MadLittleMods** 2016-05-19 22:56 UTC
