### ISSUE TITLE
Editing a deleted message does not remove the deleted indicator

### ISSUE THREAD

**Issue by jkva** [gitterHQ/gitter#1129] opened 2016-02-20 15:41 UTC
When deleting a message (arrow-up, wipe text, submit) one can re-edit the deleted message.
When submitting the change, the `deleted` class remains on the message, giving it an opacity of 0.5.

![gitter_deleted_message](https://cloud.githubusercontent.com/assets/217264/13197535/b97bbb78-d7f0-11e5-8b4c-08b80a168fe9.gif)

**Comment by MadLittleMods** [comment] 2016-02-21 05:12
Duplicate of https://github.com/gitterHQ/gitter/issues/415

**Closed by MadLittleMods** 2016-02-21 05:12 UTC

**Comment by jkva** [comment] 2016-02-21 13:01
Ah, apologies for the duplicate. I ran a search for 'deleted' but I should've searched more thoroughly.

**Comment by MadLittleMods** [comment] 2016-02-21 18:50
@jkva no worries, Your issue adds a few more keywords for future people searching that can follow the duplicate link to get to the right place.
