### ISSUE TITLE
Ctrl+Shift+Left

### ISSUE THREAD

**Issue by polyvertex** [gitterHQ/gitter#1328] opened 2016-07-03 14:59 UTC
While editing my messages on Gitter I often use `Ctrl+Shift+Left` to select a portion of the text. But since a few days maybe, it seems that this shortcut is bound to some action on Gitter's web interface (with the Chrome browser at least). Is there a way to disable or reconfigure them?

**Comment by cbj4074** [comment] 2016-07-03 16:05
Yes! I just described the exact same issue in the Desktop chat channel:

> I've noticed some less-than-ideal keyboard-related behavior in Gitter Desktop (Win) as of late.
Can't quite pin-down exactly what causes it, unfortunately
I think it has something to do with using Ctrl+Shift with the arrow keys to highlight entire words. The cursor "loses focus" and it looks like focus is off in the left-hand panel.
I have to use the mouse to click back into the input field. Happens on two different machines, just the same way on each.
Don't recall seeing the issue until this week, FWIW. Anyway, I'll provide more detail when I figure out what triggers it.

Given your description, it seems that the issue is not limited to the Desktop client.

I'm having trouble reproducing this consistently, though. Hopefully, the Gitter developers are able to reproduce it and know exactly what's causing this recent change in behavior.

Thanks for opening the issue!

**Comment by polyvertex** [comment] 2016-07-03 18:40
In case it helps, @cbj4074's description is more accurate and matches what I observed.

**Comment by thomaslevesque** [comment] 2016-07-04 18:47
I have this problem too, I was about to report it. It only happens with `Ctrl+Shift+Left` though, not `Ctrl+Shift+Right` (Firefox 47)

**Comment by polyvertex** [comment] 2016-07-04 19:56
> It only happens with `Ctrl+Shift+Left` though, not `Ctrl+Shift+Right`

Same here actually. I corrected the title and my initial message.

**Comment by cutandpastey** [comment] 2016-07-05 09:59
Thanks for reporting the issue. A fix for this has just rolled onto [next](http://next.gitter.im/). Would be great if someone can confirm the fix? Ideally I'd like to roll this into prod later today.

**Comment by cutandpastey** [comment] 2016-07-05 10:01
Also if you are using that native desktop client, instructions for using next are here: https://gitter.zendesk.com/hc/en-us/articles/203904511-Gitter-Next

**Comment by thomaslevesque** [comment] 2016-07-05 11:53
> A fix for this has just rolled onto next.

Maybe I misunderstood how to switch to next, but it doesn't seem to be fixed

**Comment by cutandpastey** [comment] 2016-07-05 12:06
If you visit [http://next.gitter.im/](http://next.gitter.im/) does it look like this?:

![screen shot 2016-07-05 at 13 00 47](https://cloud.githubusercontent.com/assets/1975139/16583923/a4ce4274-42b0-11e6-8828-6183fb23577e.png)

Also, with FF please ensure you have busted __all of the cache__ because it can be quite aggressive with holding onto assets. 

Ive just tested a fresh FF 47 install on windows and it looks fixed.

If you find the issue persists can you checkout the console within the developer tools to see if you get any errors?

**Comment by thomaslevesque** [comment] 2016-07-05 14:22
> If you visit http://next.gitter.im/ does it look like this?:

Yes, but gitter.im doesn't seem to show the "next" version, even after a `Ctrl+Shift+R`... I'll try to clear the cache. In Chrome, the issue seems to be fixed.

**Comment by thomaslevesque** [comment] 2016-07-05 14:26
OK, now I see the next version, and the issue is indeed fixed

**Comment by cutandpastey** [comment] 2016-07-05 15:44
This is now on prod so i'm closing. Feel free to re-open if there are further issues.

**Closed by cutandpastey** 2016-07-05 15:44 UTC

**Comment by thomaslevesque** [comment] 2016-07-05 15:58
Thanks for the quick fix @cutandpastey!
