### ISSUE TITLE
Any mentions look as my mentions on [next]

### ISSUE THREAD

**Issue by RReverser** [gitterHQ/gitter#1124] opened 2016-02-18 16:18 UTC
There is apparently some new bug in `next` version: any messages with mentions of any users in chats I'm participating in, show up as mentions of myself (with orange highlighting and so).

**Comment by MadLittleMods** [comment] 2016-02-18 16:27
I assume this is a duplicate of https://github.com/gitterHQ/gitter/issues/928 - Are you experiencing something outside of the issue?

**Comment by RReverser** [comment] 2016-02-18 16:45
Well, it's similar, but:
1) also getting orange highlight on new messages
2) that bug is from October 2015, and I personally didn't experience it until today, so looks like regression.

**Comment by MadLittleMods** [comment] 2016-02-19 16:33
I haven't noticed it as fixed since #928  was created.

Can you show a screenshot of what you are seeing?

**Comment by MadLittleMods** [comment] 2016-05-22 21:02
https://github.com/gitterHQ/gitter/issues/928 still exists but I can't reproduce your second different point of happening on new messages.

**Closed by MadLittleMods** 2016-05-22 21:02 UTC
