### ISSUE TITLE
Usernames that match git hashes cannot be @mentioned

### ISSUE THREAD

**Issue by dwieeb** [gitterHQ/gitter#860] opened 2015-09-16 20:37 UTC
We tried to @ mention a user in our channel by the name of `d220893` and it resulted in `null@d220893` being displayed with a broken link, because it thinks it is a short form commit hash, but could not find it in our repository.

![image](https://cloud.githubusercontent.com/assets/236501/9917707/be0adf4a-5c88-11e5-85da-a85b69065031.png)

**Comment by MadLittleMods** [comment] 2015-09-17 10:43
Duplicate of #811. Also check out #454.

Move future conversation to #811.

**Closed by MadLittleMods** 2015-09-17 10:43 UTC
