### ISSUE TITLE
3 notifications instead of one

### ISSUE THREAD

**Issue by pixelass** [gitterHQ/gitter#910] opened 2015-10-12 08:48 UTC
I get 3 notifications instead of one. This is so annoying that I have to entirely disable the feature. 

<img width="376" alt="screen shot 2015-10-12 at 1 44 04 am" src="https://cloud.githubusercontent.com/assets/1148334/10424333/48123efa-7083-11e5-9cdc-3999fedfc503.png">

**Comment by MadLittleMods** [comment] 2015-10-12 09:18
Duplicate of https://github.com/gitterHQ/gitter/issues/908. Move discussion there.

**Closed by MadLittleMods** 2015-10-12 09:18 UTC
