### ISSUE TITLE
Owners should be more noticeable

### ISSUE THREAD

**Issue by w00fz** [gitterHQ/gitter#832] opened 2015-08-25 20:47 UTC
I did open this issue on the Zendesk support tracker [[ref.](https://gitter.zendesk.com/hc/communities/public/questions/201341172-Owners-should-be-better-noticeable)], only to realize that perhaps here on GitHub is your preferred method, sorry about that. 

> It is kind of awkward when people don't realize they have been discussing issues or ideas for the project they are in, with the actual owners and developers of said project.
Owners should be better noticeable, perhaps darker nickname color or something low profile but effective.

> Also, in the People pane, owners (contributors?) have a blue bottom border but it's hardly noticeable and it's definitely not obvious what it means, especially for a guest.
I for one am confused about it, is it owners or is it contributors? When I look at it I see the border for the owners. If I open the "See All" also the contributors gets the border but if i filter and search for that contributor, the border is not there anymore.

**Comment by MadLittleMods** [comment] 2015-08-26 01:33
Duplicate of gitterHQ/gitter#227

Also see
 - gitterHQ/gitter#7
 - gitterHQ/gitter#356

**Closed by MadLittleMods** 2015-08-26 01:33 UTC
