### ISSUE TITLE
Windows 10 notification bug

### ISSUE THREAD

**Issue by ItamarShDev** [gitterHQ/gitter#1294] opened 2016-06-14 06:52 UTC
Notification sound is heard even if windows is on quiet hours
which means the sound probably comes from the app itself and not using the Windows Notification Center

**Comment by mydigitalself** [comment] 2016-06-24 14:27
Is this still happening?

**Comment by MadLittleMods** [comment] 2016-06-24 14:40
Most likely, the sound does come from within the app.

**Comment by ItamarShDev** [comment] 2016-07-10 07:30
this is still relevant
also the windows 10 banner never came up
this is why i thought from the start that there is no integration with the new notification system (yet i know nothing about this system sadly)

**Comment by kmscode** [comment] 2017-01-09 14:38
I didn't want to open a (likely) duplicate bug since the "root cause" was already identified by @MadLittleMods 

But turning off "Play a sound when a notification arrives" doesn't work either... (Settings -> System -> Notifications & Action -> Toast)

![image](https://cloud.githubusercontent.com/assets/16654335/21769993/61e17368-d64f-11e6-95d5-9a9cffd1bce1.png)

**Comment by MadLittleMods** [comment] 2017-03-24 16:29
Closed in favor of https://github.com/gitterHQ/gitter/issues/1550

**Closed by MadLittleMods** 2017-03-24 16:29 UTC
Labels: desktop
