### ISSUE TITLE
Show images in app

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1480] opened 2016-10-23 17:52 UTC
In the apps, display images when clicked on a new screen instead of opening in the web browser

Kik example: http://m.imgur.com/l1LwJRr

The picture is normal size in the chat and when clicked it goes fullscreen.

**Comment by MadLittleMods** [comment] 2016-11-02 20:52
Duplicate of https://github.com/gitterHQ/gitter/issues/858

**Closed by MadLittleMods** 2016-11-02 20:52 UTC
