### ISSUE TITLE
Adding people to private repos not working properly

### ISSUE THREAD

**Issue by malditogeek** [gitterHQ/gitter#343] opened 2014-08-28 10:37 UTC
It's possible to add users to a private repo room even if they don't have access to that repo on GitHub. This users won't be able to see any content because permissions are checked again when they try to join and they will be removed from the room; but the interface shouldn't allow to add them in the first place.

Reported by @timruffles :+1:

**Comment by artemrizhov** [comment] 2015-04-30 09:20
In my case I can't add the repo owner to the repo room associated with his private repo.

**Comment by mydigitalself** [comment] 2015-04-30 09:22
@artemrizhov that sounds like an entirely different issue. When he visits the page, does he get a 404 saying "This is not the chat you are looking for" and underneath that there is a link saying if you are looking for a private repo, you need to upgrade your GitHub scope, if he clicks that, and then visits the room, it should let him in.

**Comment by artemrizhov** [comment] 2015-04-30 09:41
I just can't add him by myself. I get a message saying he does not have permissions.

**Comment by MuhammadNe** [comment] 2015-09-21 11:04
Same happened to me as artemrizhov, if someone can tell us how to fix this problem?

**Comment by mydigitalself** [comment] 2015-09-21 11:18
@MuhammadNe can you elaborate a little on **exactly** who are you trying to add to what please and perhaps even show some screenshots of what you are seeing? I can't reproduce this at all.

**Comment by MuhammadNe** [comment] 2015-09-21 11:41
@mydigitalself My teacher create a private repository and added me to it, I created a gitter chat room so we can chat there, I clicked on "repository", then click the button to search from private repositories. Then i clicked on the private repository to create the chat room, the chat room is created, when I clicked on "add" to add people to this room and chose my teacher it tells me inside a red box "He does now have permission to join this room"

**Comment by MuhammadNe** [comment] 2015-09-21 11:42
@mydigitalself 
![gittererror](https://cloud.githubusercontent.com/assets/9402493/9991019/05bedbfe-606f-11e5-9e67-829fa9608bc2.jpg)

**Comment by mydigitalself** [comment] 2015-09-21 12:12
@MuhammadNe if you click on Create a room, can you send me a screenshot of what you see please? I just want to confirm something about how your account is behaving.

**Comment by mydigitalself** [comment] 2015-09-21 12:15
Actually, don't worry about that. I can see your account seems just fine, my mistake.

One last thing: If your teacher visits that room, can you tell me what happens please?

**Comment by MuhammadNe** [comment] 2015-09-21 12:17
Ok, I will post here what happens once he tries to visit the room. Thank you.

**Comment by MadLittleMods** [comment] 2015-12-21 02:32
@MuhammadNe Any update on the situation?

**Comment by MadLittleMods** [comment] 2016-03-24 16:45
Closing in favor of https://github.com/gitterHQ/gitter/issues/1050

**Closed by MadLittleMods** 2016-03-24 16:45 UTC
Labels: bug
