### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by CreativeWolf** [gitterHQ/gitter#1231] opened 2016-04-25 17:59 UTC
It'd be cool to have Per Room / Conversation Translation and as well Option to Translate on the Chat Window as well - Using Google API Maybe?

**Comment by MadLittleMods** [comment] 2016-05-22 20:22
Seems like a duplicate of https://github.com/gitterHQ/gitter/issues/1105

**Closed by MadLittleMods** 2016-05-22 20:22 UTC
