### ISSUE TITLE
PR/Issue shortener overrides markdown link

### ISSUE THREAD

**Issue by chrisarcand** [gitterHQ/gitter#1337] opened 2016-07-08 15:18 UTC
Gitter's Github PR/Issue shortener is great (link shows up as `SomeOrg/SomeRepo#1234`) but when you attempt to use a Github Issue/PR in a markdown link Gitter just overrides your text and puts in the usual shortened version.

That is, 

If you type `[Check out this PR!](https://github.com/someorg/somerepo/1234)`
It will ignore your text and simply display `someorg/somerepo#1234`

I don't believe the shortening should have a higher precedence than text that one writes about it.

**Comment by kbrock** [comment] 2016-07-08 15:47
Amusingly, I've run into this a number of times but thought I was the only one frustrated by it

**Comment by MadLittleMods** [comment] 2016-07-08 16:29
Duplicate of https://github.com/gitterHQ/gitter/issues/326

**Closed by MadLittleMods** 2016-07-08 16:29 UTC
