### ISSUE TITLE
Custom text shouldn't be overridden when linking to GitHub issue/PR references

### ISSUE THREAD

**Issue by isiahmeadows** [gitterHQ/gitter#1363] opened 2016-08-03 00:55 UTC
Links like below get completely overwritten, with custom text removed, on both the web client and on the Linux desktop version (64-bit):

```md
[that may be subject to change](https://github.com/ReactiveX/rxjs/issues/1829)
```

I'd expect it to look something like this:

> [that may be subject to change](https://github.com/ReactiveX/rxjs/issues/1829)

Instead, it gets completely overwritten to effectively this (with different styles, obviously):

> [ReactiveX/rxjs#1829](https://github.com/ReactiveX/rxjs/issues/1829)

It's highly annoying, and I've been running into this for a while. Could it get fixed?

**Comment by MadLittleMods** [comment] 2016-08-03 00:57
Duplicate of https://github.com/gitterHQ/gitter/issues/326

**Closed by MadLittleMods** 2016-08-03 00:57 UTC
