### ISSUE TITLE
The registered people count per community counts users multiple times

### ISSUE THREAD

**Issue by Paebbels** [gitterHQ/gitter#1535] opened 2016-11-20 07:30 UTC
Hello,

I like the new Community overview, but it counts users multiple time, if the registered in several rooms:
![image](https://cloud.githubusercontent.com/assets/956109/20461345/686b3c1c-aefb-11e6-8f9c-c111fbaab582.png)

The summary shows 49 people, but the correct number is circa 30.
Please don't count duplicates.

**Comment by MadLittleMods** [comment] 2016-11-21 12:11
Duplicate of https://github.com/gitterHQ/gitter/issues/1075

**Closed by MadLittleMods** 2016-11-21 12:11 UTC
