### ISSUE TITLE
Default notification for roomtypes

### ISSUE THREAD

**Issue by csutorasr** [gitterHQ/gitter#1740] opened 2017-07-02 11:19 UTC
I think the default notification is different for room types. If I connect to a room full of people I would not like to be informed about every message, but in personal conversation it is useful.

It would be nice to have different default notification settings for both instead of setting them every time you start a conversation.

**Comment by MadLittleMods** [comment] 2017-07-02 16:44
Duplicate of https://github.com/gitterHQ/gitter/issues/1275

**Closed by MadLittleMods** 2017-07-02 16:44 UTC
