### ISSUE TITLE
Github hooks fail to apply on new room.

### ISSUE THREAD

**Issue by trevorah** [gitterHQ/gitter#290] opened 2014-06-19 15:33 UTC
`bjz/gfx-rs` wasnt getting any github hooks coming through since creation. Perhaps caused by some weird permissions setup as room was created by `@kvark` (who couldnt access the github repos's hook settings page) but the repo was owned by `@bjz`.

**Comment by mydigitalself** [comment] 2015-01-05 10:13
I can't reproduce this, closing.

**Closed** 2015-01-05 10:13 UTC
Labels: bug
