### ISSUE TITLE
Gitter multiple sidebar with desktop notification

### ISSUE THREAD

**Issue by bridsonc** [gitterHQ/gitter#548] opened 2015-01-28 15:51 UTC
Whenever I click on a desktop notification, and gitter.im is already open in a tab, the sidebar seems to cascade. I can do this multiple times to have 2+ sidebars.

 + Browser Firefox Developer Edition 37.0a2
 + Operating system Ubuntu 14.04 LTS 

![screenshot from 2015-01-28 10 41 09](https://cloud.githubusercontent.com/assets/5834292/5940812/2fd6992a-a6db-11e4-8c78-48b813401f4d.png)

**Comment by mydigitalself** [comment] 2015-01-29 14:43
Can confirm it's not just the Developer edition. Will address soon.

**Comment by waltfy** [comment] 2015-02-02 11:44
I have just been investigating the issue this morning. I cannot seem to be able to reproduce it. Neither on `Firefox 35` nor on `Firefox Developer Edition 37.0a2`. Will put it on hold. @bridsonic, please let us know if you're still experiencing this. Thanks.

**Comment by mydigitalself** [comment] 2015-02-04 23:57
@bridsonc is this still happening for you? I was able to reproduce it and then a few days later couldn't reproduce it any longer without any change on our end.

**Comment by bridsonc** [comment] 2015-02-05 00:04
Sorry I don't have access to my Ubuntu machine right now.  I will check it out and update you ASAP

**Comment by mydigitalself** [comment] 2015-02-09 11:17
Do you mind commenting again if you are able to reproduce, I'm going to close this for now.

**Closed by mydigitalself** 2015-02-09 11:17 UTC
Labels: bug, pebble, prioritised

**Comment by bridsonc** [comment] 2015-02-10 00:23
its not happening for me anymore.  seems to be fixed!
