### ISSUE TITLE
Delete and Collapse are next to each other; too easy to misclick

### ISSUE THREAD

**Issue by Fryguy** [gitterHQ/gitter#1563] opened 2016-12-13 22:02 UTC
In the `...` menu Delete and Collapse are right next to each other.  As an admin, I've deleted someone's gist by accident when trying to collapse and I can't undo it :(

Would it be possible to either
- Add a "Are you sure you want to Delete" message?  I know people generally ignore those, but at least it's a barrier to accidental clicks.
- Make it so the deleted message is soft-deleted, but recoverable within a short window.  Some ideas to deal with this visually are
  - to insert a gray or red shaded full-width bar where the message used to be and a "Restore" link/button/`...`-menu entry, perhaps only letting Admins see it
  - to leave the message as is but shade it all in a light red, again with a "Restore" link/button/`...`-menu entry, perhaps only letting Admins see it
  - Although it no longer exists in the current Gitter, the previous version of Gitter would leave the entry placeholder but with the text "*message deleted by username*"

**Comment by MadLittleMods** [comment] 2016-12-13 22:58
@Fryguy You can use `/collapse` or `/collapse-all`

Duplicate of https://github.com/gitterHQ/gitter/issues/886

**Closed by MadLittleMods** 2016-12-13 22:58 UTC
