### ISSUE TITLE
The Spinner and UX

### ISSUE THREAD

**Issue by ScalaWilliam** [gitterHQ/gitter#599] opened 2015-03-01 23:42 UTC
When I change the channel, the I see a spinner for around a second. Is there any reason for that? I feel it to be very distracting to the eye and makes Gitter feel slow. I would prefer to see the target chatroom straight away, even if it is out of date, without seeing a spinner (... some people call it the spinner of death). I was hoping to see the spinner disappear by installing the desktop Gitter but that did not seem to do the trick.

Here's a good presentation about perceived performance. https://www.youtube.com/watch?v=88xUE9APato

I love the product by the way, this is the first thing I did not like.

Kind Regards,
William

**Comment by mydigitalself** [comment] 2015-03-02 10:12
Hey William,

The problem is you won't see the next room straight away. We are just about to start some major architecture work to enable this (basically caching room content locally). 

Before we added the spinner, there would be a noticeable delay that appeared to make the UI entirely unresponsive and would often cause people to click again.

I'm going to close this issue as it's effectively covered by a wider on-going initiative.

Mike

**Closed by mydigitalself** 2015-03-02 10:12 UTC
