### ISSUE TITLE
Ctrl+Page Up/Down triggers scrolling

### ISSUE THREAD

**Issue by pitrou** [gitterHQ/gitter#815] opened 2015-08-11 15:54 UTC
Gitter scrolls the chat pane on PageUp / PageDown. This is good. However, it also does so when the Ctrl key is pressed in addition with PageUp / PageDown. The problem is that's the shortcut for navigating between tabs, so each time I navigate to a gitter tab using those keys, it _also_ scrolls the chat pane up or down.

**Comment by MadLittleMods** [comment] 2015-08-12 00:15
I am not able to reproduce this with Chrome or Firefox on a Windows 8.1 machine.
 - `PageUp` / `PageDown`: Scrolls chat around
 - `Ctrl + PageUp/PageDown`: Switches browser tabs

**Comment by pitrou** [comment] 2015-08-12 08:29
This is with Firefox 39.0.3 under Ubuntu 15.04.

**Comment by MadLittleMods** [comment] 2015-08-12 12:04
I tested with Firefox 35.0.1 under Ubuntu 14.04 and can reproduce.

But it acts completely as desired with Chromium v43.0.2357.130 under Ubuntu 14.04.

**Comment by grahamperrin** [comment] 2016-11-11 18:29
#702

**Comment by MadLittleMods** [comment] 2016-11-11 18:32
Thanks @grahamperrin ❤️ 

Closed in favor of #702

**Closed by MadLittleMods** 2016-11-11 18:32 UTC
Labels: accessibility
