### ISSUE TITLE
Bug with nickname

### ISSUE THREAD

**Issue by SerafimArts** [gitterHQ/gitter#1100] opened 2016-02-08 10:53 UTC
Original nickname: "dead23angel". 
In mentions: "null@dead23a"
Target user: https://github.com/dead23angel

Screenshot:
![http://docs.rudev.org/stream/93fbc3bd7c18b02699a047451b00d59c](http://docs.rudev.org/stream/93fbc3bd7c18b02699a047451b00d59c)

**Comment by MadLittleMods** [comment] 2016-02-08 11:03
Duplicate of https://github.com/gitterHQ/gitter/issues/811

**Closed by MadLittleMods** 2016-02-08 11:03 UTC
