### ISSUE TITLE
hashtag as a link to a sibling room or topic, with an optional quiet marker (maybe a link back) in the targeted area 

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1569] opened 2016-12-18 07:55 UTC
Enhancement request. A variation from https://github.com/gitterHQ/gitter/issues/488, I can't tell whether this will be complementary or contentious. 

## Example

In the TrueOS lobby at https://gitter.im/trueos/Lobby?at=58563e45db9cafe918398ae5 I used hashtag 
`#Lumina` 
_assusming_ that it would automatically become a case-insensitive hyperlink to sibling room 
https://gitter.im/trueos/lumina

----

In addition I _wondered_ whehter the hashtagged mention of Lumina, in the lobby, would generate: 

- in the targeted room (Lumina), a marker of some sort; ideally a simple link back to the origin of the mention. 

### Pros and cons of cross-referencing

On the plus side, it could appeal to **residents of one room who have little or no interest in other rooms** within the organisation. 

(Lumina, the room for the desktop environment, is probably not a good example. As the DE is integral to TrueOS Desktop, so we can reasonably assume that all residents of Lumina will have at least some interest in TrueOS; in other words, expect these people to visit both rooms without encouragement.)

Down side, noise. So: if it's possible for a marker to appear in the target area **and not** be counted for notification purposes, then please default to that quiet behaviour.

**Comment by MadLittleMods** [comment] 2016-12-18 16:32
Duplicate of https://github.com/gitterHQ/gitter/issues/117

**Closed by MadLittleMods** 2016-12-18 16:32 UTC
