### ISSUE TITLE
[Suggestion] Add linenumbers to codeblocks

### ISSUE THREAD

**Issue by megaxlr** [gitterHQ/gitter#1211] opened 2016-04-12 12:07 UTC
Add linenumbers to codeblocks. This will make discussing about snippets of code easier since we will be able to refer to the line number instead of the content.

**Comment by Cp-022** [comment] 2016-04-12 12:08
+1 This needs to be done

**Comment by MadLittleMods** [comment] 2016-04-12 18:42
Duplicate of https://github.com/gitterHQ/gitter/issues/1107. Move discussion there

**Closed by MadLittleMods** 2016-04-12 18:42 UTC
