### ISSUE TITLE
Feature request: Automatic code markdown when 10+ lines

### ISSUE THREAD

**Issue by OFFLlNE** [gitterHQ/gitter#1576] opened 2017-01-12 15:26 UTC
Since I spend most of my day sitting on FreeCodeCamp/Help room, I see many people just post 30 lines of code and without using any type of backticks. Problem - difficult to read the code and sometimes spams the chat.

Solution:
When someone is posting code that is 5+ / 10+ lines, then it will be automatically wrapped into proper backticks (\``` + \```).

Another feature that would be nice is with links, that when a link has over 100 characters, then it will be put into proper link markdown (\[Comment You want to add](Link))

**Comment by DarrenfJ** [comment] 2017-01-12 16:23
Additional feature is that when it does that automatic formatting it also included a chatBot like link to some wiki info on how to you it yourself "You can do this ode formatting yourself sing markdown: [insert link to helpWiki]"

**Comment by se5a** [comment] 2017-06-01 17:13
what about having gitter automatically create a gist when a large amount of text is posted, and adding a link instead?

**Comment by MadLittleMods** [comment] 2017-06-02 08:16
Duplicate of https://github.com/gitterHQ/gitter/issues/1246

**Closed by MadLittleMods** 2017-06-02 08:16 UTC
