### ISSUE TITLE
Show active/online users first

### ISSUE THREAD

**Issue by ffxsam** [gitterHQ/gitter#927] opened 2015-10-23 01:53 UTC
On the sidebar (in both desktop and web apps), it would be nice if users who were active/online were shown first.

![meteor_meteor_-_gitter](https://cloud.githubusercontent.com/assets/12532733/10682650/245bd526-78ed-11e5-96a3-75ebd853234c.jpg)

Unless I'm misunderstanding the orange dots.. (green dot = online/active?)

**Comment by MadLittleMods** [comment] 2015-10-23 02:40
Duplicate of https://github.com/gitterHQ/gitter/issues/124. Move discussion there :)

**Closed by MadLittleMods** 2015-10-23 02:40 UTC
