### ISSUE TITLE
iOS Conversation rooms duplicate when there are notifications

### ISSUE THREAD

**Issue by gin93r** [gitterHQ/gitter#1470] opened 2016-10-18 13:26 UTC
Tough one to summarize in the title.

Home Screen (All Conversations):
If there are messages/mentions in one of the rooms, the first item and the second item in the list are the same. I've noticed that the duplicate room will take the place of another room, essentially dropping the room until the messages are read.

Once the messages are read and the screen is refreshed, the issue will resolve itself.

Example (I follow 3 rooms)

- thoughtbot/neat
- jescalan/roots
- vuejs/vue

When I would get notifications for jescalan/roots, my list would be:

- jescalan/roots
- jescalan/roots
- vuejs/vue

Hope this is descriptive enough.

**Comment by MadLittleMods** [comment] 2016-10-18 15:41
Most likely duplicate of https://github.com/gitterHQ/gitter/issues/1453

**Comment by gin93r** [comment] 2016-10-19 18:50
@MadLittleMods Yup. Looks like it's the same issue. :) Would you prefer this issue closed then?

**Closed** 2016-10-19 19:11 UTC
Labels: bug, ios
