### ISSUE TITLE
Disable issue linking in private chat rooms

### ISSUE THREAD

**Issue by adambuczynski** [gitterHQ/gitter#1104] opened 2016-02-09 01:52 UTC
In a private chat (not linked to any repository), if you type `#1` or any other number it tries to link it to an issue. This is not necessary in private chats, as there is no linked repository.

![image](https://cloud.githubusercontent.com/assets/490562/12905548/e0745a62-cf3c-11e5-9cff-9c7e5e200219.png)

**Comment by MadLittleMods** [comment] 2016-02-09 01:54
@adambuczynski This is currently on Gitter [`next`](http://next.gitter.im/) and will be rolled out to product when we cut the next release. Duplicate of https://github.com/gitterHQ/gitter/issues/1089

**Comment by adambuczynski** [comment] 2016-02-09 01:55
Thank you

**Closed by MadLittleMods** 2016-02-09 01:54 UTC
