### ISSUE TITLE
Can't remove rooms from list of rooms in Android App

### ISSUE THREAD

**Issue by adambuczynski** [gitterHQ/gitter#1118] opened 2016-02-16 21:44 UTC
Gitter for Android is showing a list of rooms in the overview, but it's displaying *all* the rooms I have ever been in, even though I already left the room (on the desktop client).

Could we have an option to either swipe to remove a room, or touch & hold for remove option to show up? I don't like old rooms cluttering up my list.

Thanks!

**Comment by MadLittleMods** [comment] 2016-02-17 02:31
Duplicate of https://github.com/gitterHQ/gitter/issues/468

**Closed by MadLittleMods** 2016-02-17 02:31 UTC

**Comment by adambuczynski** [comment] 2016-02-17 02:38
Sorry, missed that issue. A bit depressing it's been open for more than a year already though ;)
Would you guys be interested in some help with the project?

**Comment by MadLittleMods** [comment] 2016-02-17 02:45
@adambuczynski We are always striving to get parity with the webapp and have been doing iterations switching between iOS and Android development. We prioritize features based on interest and usefulness. Our mobile apps are currently not open source but really appreciate the bug reports or noting what features you are missing. Feel free to give the issue a `:+1:` to help prioritize it.

**Comment by adambuczynski** [comment] 2016-02-17 02:45
Cheers, thanks.
