### ISSUE TITLE
📱iOS - Show User Names

### ISSUE THREAD

**Issue by cifinn** [gitterHQ/gitter#1461] opened 2016-10-05 12:01 UTC
Not just real names. It would be nice to see both especially when @ing someone. You need to know the users, which is quite the overhead, given that sometimes typing their real name (after an @) doesn't show the user.

**Comment by TheDiamondYT1** [comment] 2016-10-21 20:40
The iOS chat screen is just a webview of the gitter mobile site. Maybe you should request that to be changed

**Comment by MadLittleMods** [comment] 2016-10-21 22:24
Duplicate of https://github.com/gitterHQ/gitter/issues/1325

**Closed by MadLittleMods** 2016-10-21 22:24 UTC
