### ISSUE TITLE
Gitter using the discrete graphics card on my MacBook Pro

### ISSUE THREAD

**Issue by asmeurer** [gitterHQ/gitter#1669] opened 2017-04-11 18:14 UTC
I have a Mid 2012 Retina MacBook Pro, which has automatically switching discrete and integrated graphics cards. I use https://gfx.io/ to tell me when an app switches from the integrated card to the discrete card (the integrated card uses less battery, but the discrete card has better performance for graphics intensive apps). 

https://gfx.io/ tells me that gitter is forcing the discrete card when I have automatic switching enabled. This happens both I open gitter in a Chrome tab instead or if I use the Mac app. As gitter is not a graphics intensive application, I wouldn't expect it to use this, and it causes more battery drain than necessary.

**Comment by MadLittleMods** [comment] 2017-04-11 18:18
Duplicate of https://github.com/gitterHQ/desktop/issues/183 ?

**Comment by mydigitalself** [comment] 2017-04-11 18:21
Translate3d css things perhaps @MadLittleMods ?

**Comment by MadLittleMods** [comment] 2017-04-11 18:25
@asmeurer @mydigitalself Probably any GPU accelerated property.

**Comment by MadLittleMods** [comment] 2017-04-11 19:23
Closing in favor of https://github.com/gitterHQ/desktop/issues/183

**Closed by MadLittleMods** 2017-04-11 19:23 UTC
