### ISSUE TITLE
Collapse very long messages

### ISSUE THREAD

**Issue by michael-krebs** [gitterHQ/gitter#1071] opened 2016-01-17 02:06 UTC
I'm in the FreeCodeCamp room a lot. People posting code outside of a code block happens very frequently, and their message often takes up an entire window. A feature which could collapse lines greater than 10 lines in length would be very helpful.

**Comment by MadLittleMods** [comment] 2016-01-19 01:25
Duplicate of https://github.com/gitterHQ/gitter/issues/515

**Closed by MadLittleMods** 2016-01-19 01:25 UTC
