### ISSUE TITLE
Hide option for suggested rooms not working.

### ISSUE THREAD

**Issue by souravbadami** [gitterHQ/gitter#1229] opened 2016-04-24 14:59 UTC
![screenshot from 2016-04-24 20 23 44](https://cloud.githubusercontent.com/assets/11073943/14768255/92a2fce0-0a5a-11e6-965c-9982c476248f.png)

**Issue**: The suggested room panel on the left sidebar has a hide option which is not working.
**Browser**: Mozilla Firefox V45.0 / Google Chrome V49.0.2623.108
**Os**: Ubuntu 14.04

**Comment by MadLittleMods** [comment] 2016-04-29 20:24
Duplicate of https://github.com/gitterHQ/gitter/issues/968

**Closed by MadLittleMods** 2016-04-29 20:24 UTC
