### ISSUE TITLE
disable email notifications from gitter.im website

### ISSUE THREAD

**Issue by ryenus** [gitterHQ/gitter#1073] opened 2016-01-18 02:54 UTC
Requesting for those (including me) who cannot find the entry to disable notification emails in gitter.im website.

Thought this should be part of user profile and/or room settings, but not yet.

In the meantime, users can look for the Unsubscribe link in notification emails.

Thanks

**Comment by MadLittleMods** [comment] 2016-01-19 01:33
Duplicate of https://github.com/gitterHQ/gitter/issues/622

**Closed by MadLittleMods** 2016-01-19 01:33 UTC
