### ISSUE TITLE
Collapsable left navigation

### ISSUE THREAD

**Issue by tjconcept** [gitterHQ/gitter#604] opened 2015-03-03 18:11 UTC
Combined with #603.

I am sorry for this storm of ideas, but it is really a compliment to your product - I want it to succeed. I hope you can use some of them.

**Comment by MadLittleMods** [comment] 2015-10-14 09:31
Duplicate of https://github.com/gitterHQ/gitter/issues/296

**Closed by MadLittleMods** 2015-10-14 09:31 UTC
Labels: enhancement
