### ISSUE TITLE
Color PR links the same as GitHub

### ISSUE THREAD

**Issue by chfast** [gitterHQ/gitter#1214] opened 2016-04-14 08:21 UTC
GitHub colors merged PRs differently than closed PRs. Examples:
https://github.com/gitterHQ/node-gitter/pull/13
https://github.com/gitterHQ/node-gitter/pull/11

It would be nice to have purple links to merged PRs in Gitter chat.

**Comment by MadLittleMods** [comment] 2016-04-14 12:36
Duplicate of https://github.com/gitterHQ/gitter/issues/418

**Closed by MadLittleMods** 2016-04-14 12:36 UTC
