### ISSUE TITLE
Have option to show other users when you are typing

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [gitterHQ/gitter#1484] opened 2016-10-27 16:28 UTC
Like with most other messaging programs I think it would be nice if there were at least a setting which would allow one to make it so that other users can see when they are typing.

**Comment by MadLittleMods** [comment] 2016-10-28 05:19
Duplicate of https://github.com/gitterHQ/gitter/issues/261

Also see https://github.com/gitterHQ/gitter/issues/256

**Closed by MadLittleMods** 2016-10-28 05:19 UTC
