### ISSUE TITLE
Activity feed not updating

### ISSUE THREAD

**Issue by N8Solutions** [gitterHQ/gitter#1598] opened 2017-01-30 08:36 UTC
No matter what room I am viewing the activity feed is **NOT** showing anything past **January 26th**. I have logged in from different browsers on the same computer, tried using different computers, even logging in using my iPad, all with the same result.

**Comment by schas002** [comment] 2017-01-30 08:44
Voting to close as duplicate of #1596, but still, nice issue :)

**Closed** 2017-01-30 09:23 UTC
