### ISSUE TITLE
Disabling emoticons

### ISSUE THREAD

**Issue by ScalaWilliam** [gitterHQ/gitter#601] opened 2015-03-02 00:18 UTC
My chat-friends on Gitter, and also me, find that the emoticons in Gitter chats are too distracting. Some of these emoticons I dislike too.

We'd like at least the option to switch off those colourful images and just stick to plain text ":)", ":D", ";)", etc.

What's the point of ":sagittarius:"  and ":saxophone:" ? 

":+1:", ":-1:", ":clap:" are great though, I wouldn't want to disable them. They don't interfere with the reflexive ";)" that we've gotten used to writing following a decade of IRC.

**Comment by mydigitalself** [comment] 2015-03-02 10:16
We inherit the full official set of emoji (http://www.emoji-cheat-sheet.com/), whilst some of them may not be used that frequently.

If we were to disable emoji, it would be a blanket disable. I don't think it's really fair to pick out three you might like and want to keep those but not the rest, can you imagine if you multiply that opinion across the entire userbase?

**Comment by ScalaWilliam** [comment] 2015-03-02 16:35
I would prefer a blanket disable. At least would prefer to have a choice of emoticons or no emoticons in the app.

**Comment by lucasgautheron** [comment] 2015-03-02 16:42
I would like to see an option to turn all of them off, at least. Some of them look clearly useless, and for the others, well ; it is annoying when the image replacement does not reflect what you had in mind.

**Comment by fancellu** [comment] 2015-03-02 17:12
I agree, ability to blanket disable. When you're trying to show some code and it thinks it knows best, argh.

**Comment by mydigitalself** [comment] 2015-03-02 17:16
@fancellu codepens shouldn't convert emoji

```:)```

**Comment by astorije** [comment] 2015-05-28 23:54
:+1: 
When I want to display :-), I type `:-)`. When I want to display a colorful emoji :smile:, I type `:smile:`.

Actually, @mydigitalself, even though you inherit the full set of http://www.emoji-cheat-sheet.com/, I think the texts to get them should only be the ones next to the emojis, not alternatives such as :-), ;-), ...

Can we haz? :-)

**Comment by vermiculus** [comment] 2015-07-11 17:16
> the texts to get them should only be the ones next to the emojis, not alternatives such as :-), ;-), ...

*Pretty please.*

**Comment by iammarkoradak** [comment] 2015-09-07 15:46
+1

**Comment by MadLittleMods** [comment] 2016-02-04 13:48
Duplicate of https://github.com/gitterHQ/gitter/issues/164

**Closed by MadLittleMods** 2016-02-04 13:48 UTC
