### ISSUE TITLE
Getting no Notification on Android & no Notification Settings

### ISSUE THREAD

**Issue by c33s** [gitterHQ/gitter#1145] opened 2016-02-26 03:18 UTC
I installed Gitter on my mobile phone today and I miss the notification settings or even any configuration options in the app. The room menu only shows "Leave this room", the main menu only shows "sign out", and the hardware menu button only shows "Search"

Is there a hidden requirement to Google Play Services/Google Cloud Messaging?

Would be awesome to add an alternative push system for google free phones, https://github.com/gitterHQ/gitter/issues/856#issuecomment-189084795

**Comment by MadLittleMods** [comment] 2016-02-26 03:20
Duplicate of https://github.com/gitterHQ/gitter/issues/848

**Closed by MadLittleMods** 2016-02-26 03:20 UTC

**Comment by c33s** [comment] 2016-02-26 03:24
@MadLittleMods don't think its a duplicate. the other issue only discusses the settings menu.
this issue adresses three things:
- missing menu
- no notification
- question if GCM is required

please reopen or please add the related issues so i can watch them

**Comment by MadLittleMods** [comment] 2016-02-26 03:27
You should create separate issues for each enhancment/feature/bug.

In this case, the notification settings and menu for them are covered by https://github.com/gitterHQ/gitter/issues/848 - And you asked about the google play store requirement here https://github.com/gitterHQ/gitter/issues/856#issuecomment-189084795 where I also linked in your OP.

**Comment by c33s** [comment] 2016-02-26 03:28
thank you very much
