### ISSUE TITLE
Chrome App loses chat window focus when Alt-Tabbing away

### ISSUE THREAD

**Issue by fiznool** [gitterHQ/gitter#349] opened 2014-09-04 21:27 UTC
If you have the chat window focussed in the Chrome App, try Alt-Tabbing away from the window, then back in again. Tested on Ubuntu 14.04.

You'll notice the chat area is no longer focussed. This, along with #348 make using the chat client in the Chome App difficult, as every time you Alt-Tab back into the chat client, you need to click in the chat area with the mouse to write anything.

**Comment by MadLittleMods** [comment] 2015-08-02 12:08
Duplicate of #348.

**Closed by MadLittleMods** 2015-08-02 12:08 UTC
Labels: bug
