### ISSUE TITLE
Make the people sidebar smaller or resizable when widening the window

### ISSUE THREAD

**Issue by adambuczynski** [gitterHQ/gitter#1143] opened 2016-02-24 19:48 UTC
That's a lot of wasted screen real estate on the right side:

![image](https://cloud.githubusercontent.com/assets/490562/13298617/6c32ecf6-db9c-11e5-9f35-65906deb8639.png)

I prefer the narrow band that shows up when you make the window more narrow:

![image](https://cloud.githubusercontent.com/assets/490562/13298631/7ae90eba-db9c-11e5-866b-f44affbcdb75.png)

Usually, when you make the window wider, you do that because you want to see more of the chat area. Instead, we get to see more white space on the right. Could we disable this or make it resizable?

**Comment by MadLittleMods** [comment] 2016-02-25 18:29
Duplicate of https://github.com/gitterHQ/gitter/issues/296 and https://github.com/gitterHQ/gitter/issues/253.

The new left menu that we are bringing to production soon will be collapsible.

**Closed by MadLittleMods** 2016-02-25 18:29 UTC

**Comment by adambuczynski** [comment] 2016-02-25 18:53
Thanks!

**Comment by adambuczynski** [comment] 2016-05-12 22:08
@MadLittleMods I'd like to reopen this issue, since the new design of the app has done nothing to address this issue.

The people bar on the right is still uncollapsible and unresizable.

**Comment by MadLittleMods** [comment] 2016-05-12 23:12
@adambuczynski The latest update addresses the left menu not the right sidebar. The issues linked above cover the issue and you can track those to know when it happens.

**Comment by adambuczynski** [comment] 2016-05-12 23:14
Thanks I have subscribed there. I assumed you'd be pushing all interface updates out at once.
