### ISSUE TITLE
Insert recent mentions in the MESSAGES IN ORG/REPO

### ISSUE THREAD

**Issue by srisankethu** [gitterHQ/gitter#1058] opened 2016-01-08 16:27 UTC
@MadLittleMods I was just searching your name in the search box and I found this
![screenshot 14](https://cloud.githubusercontent.com/assets/12644108/12202886/16c83466-b652-11e5-8a6d-4f50d22e267f.png)
your recent mentions aren't there but as I scrolled down....
![screenshot 15](https://cloud.githubusercontent.com/assets/12644108/12202942/6a7ff9ea-b652-11e5-90c9-3d384fcfb3b0.png)
last two recent mentions in the room were mentioned at the bottom.It just seemed improper to me.

**Comment by MadLittleMods** [comment] 2016-01-11 13:51
Duplicate of https://github.com/gitterHQ/gitter/issues/566

**Closed by MadLittleMods** 2016-01-11 13:51 UTC
