### ISSUE TITLE
misattribution (a post edited by me with Android appears to be sent by poster before me)

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1419] opened 2016-09-02 00:43 UTC
![misattribution](https://cloud.githubusercontent.com/assets/192271/18188999/a920e238-70ae-11e6-9376-a7a6e5c6f3a8.png)

https://gitter.im/trueos/Lobby?at=57c8c8176efec7117c9e8225

When I load that URL now I see, for a **split-second** – 

> grahamperrin Fixed my HP prob

– then it truncates to: 

> Fixed my HP prob

That's as viewed with Firefox and (if it helps) the text is purple. 

Another reader observes the mis-attribution with Chromium.

**Comment by MadLittleMods** [comment] 2016-09-02 07:13
Duplicate of https://github.com/gitterHQ/gitter/issues/1004

**Closed by MadLittleMods** 2016-09-02 07:13 UTC
