### ISSUE TITLE
If a user searches himself in the gitter search option, the app is opening multiple windows and there is no coming out of it!

### ISSUE THREAD

**Issue by igniteram** [gitterHQ/gitter#1356] opened 2016-07-26 13:28 UTC
I feel this is a bug !

**Issue:** User searches himself in the app and we can see multiple windows of the app and no escape from this
**Environment :** Mac OSX, both gitter web & desktop app.
Please find the screenshots!

**desktop screen**

<img width="1431" alt="screen shot 2016-07-26 at 6 48 05 pm" src="https://cloud.githubusercontent.com/assets/15998104/17139560/a9ff8ee8-5362-11e6-92c2-c0a1060003f7.png">

**web screen**

<img width="1440" alt="screen shot 2016-07-26 at 6 52 53 pm" src="https://cloud.githubusercontent.com/assets/15998104/17139571/b72b715e-5362-11e6-8a67-2a23816230e6.png">

**Comment by MadLittleMods** [comment] 2016-07-26 13:39
Duplicate of https://github.com/gitterHQ/gitter/issues/1277

**Closed by MadLittleMods** 2016-07-26 13:39 UTC
