### ISSUE TITLE
New channel modal won't go away

### ISSUE THREAD

**Issue by AgDude** [gitterHQ/gitter#685] opened 2015-05-07 18:08 UTC
I just created a new private channel, the modal stayed open, and won't close with either the cancel or "x" buttons. I do have gitter open in two tabs at the moment.

**Comment by mydigitalself** [comment] 2015-05-11 16:20
Hey, I can't reproduce this at all, is it still happening?

**Comment by MadLittleMods** [comment] 2015-07-27 10:19
Closing because I can not reproduce and no reply.

**Closed by MadLittleMods** 2015-07-27 10:19 UTC
