### ISSUE TITLE
Delete button confirmation

### ISSUE THREAD

**Issue by HoBi** [gitterHQ/gitter#1039] opened 2015-12-25 12:39 UTC
It would be really nice to add some confirmation step when you click on delete button on you comment, because you can not undelete your comment and it is under edit button, which makes it super easy to make misclick.

**Comment by MadLittleMods** [comment] 2015-12-25 15:44
Duplicate of https://github.com/gitterHQ/gitter/issues/886, move discussion there.

**Closed by MadLittleMods** 2015-12-25 15:44 UTC
