### ISSUE TITLE
Chat message area collapsed

### ISSUE THREAD

**Issue by spencern** [gitterHQ/gitter#1150] opened 2016-03-01 23:43 UTC
Chat message area collapsed in the OSX desktop app v1.162. Started happening around ~3:30pm MST on 2016-3-1.

Symptoms:
* Chat messages pane is either collapsed, missing, or no longer populated.
![image](https://cloud.githubusercontent.com/assets/1203639/13445847/00f3b2c0-dfcc-11e5-8fa2-7c6b56c4f060.png)

* Chatters and Issue history pane is tiny
![image](https://cloud.githubusercontent.com/assets/1203639/13445893/4aa55c2a-dfcc-11e5-889c-a420e26014bb.png)

Errors from the console:
```
[Warning] Unexpected CSS token: ; (router-chat.css, line 9)
[Warning] The page at https://gitter.im/gitterHQ/gitter displayed insecure content from http://beta-internal:8080/job/gitter-webapp-build-step/4476/artifact/output/maps/router-chat.css.map. (gitter, line 0)
[Warning] The page at https://gitter.im/gitterHQ/gitter displayed insecure content from http://beta-internal:8080/job/gitter-webapp-build-step/4476/artifact/output/maps/router-app.css.map. (gitter, line 0)
[Warning] The page at https://gitter.im/gitterHQ/gitter displayed insecure content from http://beta-internal:8080/job/gitter-webapp-build-step/4476/artifact/output/maps/router-app.js.map. (gitter, line 0)
[Warning] The page at https://gitter.im/gitterHQ/gitter displayed insecure content from http://beta-internal:8080/job/gitter-webapp-build-step/4476/artifact/output/maps/router-chat.js.map. (gitter, line 0)
[Error] Failed to load resource: A server with the specified hostname could not be found. (router-chat.css.map, line 0)
[Error] Failed to load resource: A server with the specified hostname could not be found. (router-app.css.map, line 0)
```

**Comment by MadLittleMods** [comment] 2016-03-02 01:36
@isnotinvain was also able to reproduce this https://gitter.im/gitterHQ/gitter?at=56d60298f760676329bab937

**Comment by mydigitalself** [comment] 2016-03-02 12:58
Is this experienced in regular Safari too?

**Comment by MadLittleMods** [comment] 2016-03-02 13:05
@mydigitalself I looked at it yesterday and just now and it looks fine for me in Safari. I am curious if it is broken for @spencern or @isnotinvain though.

**Comment by mydigitalself** [comment] 2016-03-02 13:24
Yeah I was curious if perhaps they have something that's a bit funny with their Safari - perhaps even an older version that's causing some undiscovered issues.

**Comment by spencern** [comment] 2016-03-02 15:54
Works fine for me in Safari and Chrome.
On OSX 10.9.5
Safari: Version 9.0.3 (9537.86.4.4)

**Comment by RubenVerborgh** [comment] 2016-03-02 18:11
Have the same issue with the standalone app.

**Comment by mydigitalself** [comment] 2016-03-02 18:28
@spencern do you see any other errors in the console when you switch room perhaps?

None of those other errors would seem to point to the issue, which we just can't reproduce.

Also, may be worthwhile opening the Network panel in that inspector, switching rooms and seeing if there are any obvious errors there. I'm wondering if you're hitting a stale DNS entry and some of the JavaScript resources are failing to come down. Out of interest, what do you use for DNS?

**Comment by RubenVerborgh** [comment] 2016-03-02 18:29
I found something:
```
Failed to load resource: A server with the specified hostname could not be found.
```

**Comment by RubenVerborgh** [comment] 2016-03-02 18:33
The bad stylesheet is `https://cdn02.gitter.im/_s/7de8dad/styles/router-app.css`.

**Comment by mydigitalself** [comment] 2016-03-02 18:45
@RubenVerborgh so that http request is coming back as failing on the hostname? That makes no sense, I assume other resources are being loaded from the same domain... 

I also assume you can load that just fine in Safari/Chrome?

**Comment by RubenVerborgh** [comment] 2016-03-02 18:46
Might just be a debug leftover; it's only the `.map` files that fail on the hostname, no files that are actually needed it seems. Everything loads fine in Safari/Chrome itself.

**Comment by isnotinvain** [comment] 2016-03-02 19:56
Hello!

I am still seeing this in my osx desktop client. I can confirm that gitter works just fine in safari and chrome. Let me know if you want any other info, I do get the same logs posted above about bad hostname and also the css warning.

**Comment by isnotinvain** [comment] 2016-03-02 20:00
I opened up the 'timing' tab and went to network requests, I'm not too familiar with this but there was one red item here (which also seemed to take a long time), maybe this is the app failing to load the chat data or something? 

<img width="980" alt="screen shot 2016-03-02 at 11 58 50 am" src="https://cloud.githubusercontent.com/assets/372969/13473473/5da4ba30-e06e-11e5-972b-d2629ddc77d2.png">

**Comment by RubenVerborgh** [comment] 2016-03-02 20:29
I looked at the HTML source and the chat data _is_ loading. I can see all messages in HTML. The problem must be CSS.

**Comment by mydigitalself** [comment] 2016-03-02 22:02
In the inspector, can you go to `Resources` 

And then in Frames -> ~chat -> Stylesheets -> router-chat.css
And in Stylesheets -> router-app.css

Would it be possible for you to attach those two files to this issue please?

**Comment by RubenVerborgh** [comment] 2016-03-02 22:28
[router-app.css](https://github.com/gitterHQ/gitter/files/155810/router-app.css.txt)
[router-chat.css](https://github.com/gitterHQ/gitter/files/155811/router-chat.css.txt)

**Comment by RubenVerborgh** [comment] 2016-03-02 22:30
Something strange: the inspector reports

```
[Warning] Unexpected CSS token: ; (router-chat.css, line 9)
```

Line 9 is also highlighted. However, it looks like an empty line and there is no trace of any semicolon whatsoever.

**Comment by MadLittleMods** [comment] 2016-03-02 22:31
@RubenVerborgh Please note that those `.map` files are just the sourcemaps we have pointing to an internal URL and do not matter.

The `[Warning] Unexpected CSS token: ; (router-chat.css, line 9)` is the only thing I could see in @isnotinvain output as well yesterday when he shared it to me.

**Comment by RubenVerborgh** [comment] 2016-03-02 22:37
Let me redo the CSS files without pretty-print, just a sec.

**Comment by RubenVerborgh** [comment] 2016-03-02 22:38
[router-app.css](https://github.com/gitterHQ/gitter/files/155826/router-app.css.txt)
[router-chat.css](https://github.com/gitterHQ/gitter/files/155827/router-chat.css.txt)

**Comment by RubenVerborgh** [comment] 2016-03-02 22:43
I note that the original poster and myself are both not on the latest version of OSX. Running 10.9.5 here. Maybe it needs a specific version for reproduction.

**Comment by mydigitalself** [comment] 2016-03-02 22:55
> 10.9.5

Ahhh, good clue, thanks.

**Comment by mydigitalself** [comment] 2016-03-02 22:56
Purely out of curiosity, is there a reason you haven't updated?

**Comment by RubenVerborgh** [comment] 2016-03-02 22:56
Eventually, it seems to come down to the fact that `height: 100%` on `.trpContentPanel` does not have the intended effect. Even though its parent `div.chat-app` receives an actual height (looking at the "computed value"), its child does not take it. Manually changing height into a fixed pixel value works.

In the Safari _browser_, the child correctly handles `height: 100%` .

**Comment by RubenVerborgh** [comment] 2016-03-02 22:58
@mydigitalself I didn't update because every OSX update after Snow Leopard has made my computer worse, unfortunately. I've never been as happy as I was back then, and it already cost me an HDD and RAM update. I only upgrade when I can't run the software I need to run, which unfortunately let me to 10.9.5. Also, the new UI is plain ugly. I want Aqua back :smile:

**Comment by spencern** [comment] 2016-03-02 23:28
I'm in the same boat as @RubenVerborgh -  I haven't found that upgrading OSX is always the most stable process and since all of my dev software works fine now, I haven't seen a reason to deal with the change. It's getting to the point where I feel like I'll be needing to upgrade soon as many new OSX enhancement apps depend on 10.10 or better. 

Do we think that 10.9.5 is probably the culprit?

**Comment by mydigitalself** [comment] 2016-03-03 10:07
> Do we think that 10.9.5 is probably the culprit?

Hard to tell, need to try get our hands on one. The odd thing is that the app is effectively embedded Safari, which is working just fine and there's been no update to Safari and no update in our code that touches that area. The only update that went out on the day when it started happening was a JavaScript update for mobile and I can't see how that would be related.

**Comment by hyperknot** [comment] 2016-03-04 12:26
I can confirm the same bug on OS X 10.9.5. since about a week. Safari works fine on the same system.

**Comment by hyperknot** [comment] 2016-03-04 12:33
Some ways to show the chat panel, although it doesn't make it functional (no scrolling, no input), but probably related to the bug:
- uncheck .trpChatPanel / height, or position
- uncheck .trpChatContainer / height or overflow
- uncheck .trpContentPanel / position -> make the scroll work

**Comment by mydigitalself** [comment] 2016-03-04 13:01
Can you check this as well please. Again, inside the inspector/console type

`window.navigator.userAgent` and paste the output here please

I've also pushed a fix the remove that CSS warning error and interested to see if it's had any effect - so if you restart your app now, let me know what's happening.

**Comment by hyperknot** [comment] 2016-03-04 13:04
The css warning is not present, but it didn't have any effect.

This is the UA: `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.78.2 (KHTML, like Gecko) Gitter/1.162"`

**Comment by mydigitalself** [comment] 2016-03-04 13:17
@hyperknot are you on Next?

**Comment by hyperknot** [comment] 2016-03-04 13:21
@mydigitalself not on next.

**Comment by mydigitalself** [comment] 2016-03-04 14:15
Right. That wasn't the issue. Found the issue. *sigh*

Mavericks is effectively embedding Safari 7 in our app, and we're starting to make use of `calc` and viewport units, which aren't supported.

Trying something else now, I'll let you know shortly.

**Comment by mydigitalself** [comment] 2016-03-04 14:48
Right, @hyperknot @spencern @RubenVerborgh @isnotinvain what happens now if you restart your app?

(Sorry, still not able to get an environment setup, so having to try and emulate it in strange ways).

**Comment by hyperknot** [comment] 2016-03-04 14:49
@mydigitalself it works now! I'll report back if there are any ongoing bugs present which I cannot see now.

**Comment by hyperknot** [comment] 2016-03-04 14:50
@mydigitalself the user list is still missing: 
![image](https://cloud.githubusercontent.com/assets/494223/13530248/c2bc5f32-e220-11e5-86cf-142dc6c606f9.png)

**Comment by mydigitalself** [comment] 2016-03-04 14:51
@hyperknot great! yeah i thought there may still be issues with the user list, but now I know what to look for and should be able to sort that one out too.

**Comment by geoffjentry** [comment] 2016-03-04 16:10
Having this issue on 10.9.5, works fine in chrome and on safari though

**Comment by mydigitalself** [comment] 2016-03-04 16:12
@geoffjentry you mean you're still experiencing the issue with the chat area after a restart of the app - or are you referring to the right bit where the contacts should be?

**Comment by geoffjentry** [comment] 2016-03-04 16:59
@mydigitalself Actually I apologize, I chimed in with the version info prior to verifying that the problem is still happening. I see the text now but not the user list on the right

**Comment by RubenVerborgh** [comment] 2016-03-04 17:24
Works perfect again for me.

**Comment by spencern** [comment] 2016-03-05 06:34
Chat panel is working for me now too! Also missing the user list still.

**Closed** 2016-03-18 16:20 UTC
Labels: bug, desktop, mac

**Comment by isnotinvain** [comment] 2016-03-18 18:10
@mydigitalself thanks a lot!
