### ISSUE TITLE
No trample on inline text links when using references

### ISSUE THREAD

**Issue by jodizzle** [gitterHQ/gitter#896] opened 2015-10-05 09:35 UTC
Trying to turn a link to a commit into an inline link doesn't seem to work.  E.g., typing

```
https://github.com/jodizzle/termloop/commit/c3078e1
```

Produces the normally flavored https://github.com/jodizzle/termloop/commit/c3078e1, but typing
```
[here](https://github.com/jodizzle/termloop/commit/c3078e1)
```

does not produce "[here](https://github.com/jodizzle/termloop/commit/c3078e1)", it produces https://github.com/jodizzle/termloop/commit/c3078e1 and seemingly just deletes/overwrites the "here" text.

**Comment by MadLittleMods** [comment] 2015-10-05 10:31
I mentioned this in #826 but this separate issue will serve as a better way to track this.

> Please note that this enhancment should not trample linking text, etc with markdown unlike the current issue/PR links where they just show the rich snippet instead of just linking the text.
> #826

**Comment by MadLittleMods** [comment] 2016-02-04 22:05
Duplicate of https://github.com/gitterHQ/gitter/issues/326

**Closed by MadLittleMods** 2016-02-04 22:05 UTC
Labels: enhancement
