### ISSUE TITLE
Allow blocking/ignoring of users

### ISSUE THREAD

**Issue by SeventhSonOfASeventhSon** [gitterHQ/gitter#1616] opened 2017-03-05 14:37 UTC
A feature which I would find highly useful would be one that would allow you to block and therefore prevent other users from messaging or mentioning you. So an ignoring or blocking feature would be nice so that I don't have to get all the stuff. Perhaps it could even get the list of block people from GitHub?

**Comment by grahamperrin** [comment] 2017-03-06 08:12
This enhancement request is probably a duplicate of #370

**Comment by MadLittleMods** [comment] 2017-03-06 16:20
Thanks @grahamperrin 

Duplicate of #370

**Closed by MadLittleMods** 2017-03-06 16:20 UTC

**Comment by WORMSS** [comment] 2017-04-12 15:40
@MadLittleMods so.. issue 1616 ( ONE THOUSAND and SIXTEEN ) is a duplicate a issue that is over 3 years old.. What does that tell you?? That it's not fixed!
