### ISSUE TITLE
Windows Gitter app keeps crashing/exiting

### ISSUE THREAD

**Issue by pfn** [gitterHQ/gitter#1097] opened 2016-02-05 16:46 UTC
since #664 is closed, opening a new ticket since this still occurs, and has been forever. mostly happens around notifications of new messages.

**Comment by MadLittleMods** [comment] 2016-02-05 17:04
Duplicate of https://github.com/gitterHQ/desktop/issues/32. Move discussion there

**Closed by MadLittleMods** 2016-02-05 17:04 UTC
