### ISSUE TITLE
Show content of GitHub comments on PRs and Issues 

### ISSUE THREAD

**Issue by radix** [gitterHQ/gitter#545] opened 2015-01-26 19:45 UTC
Right now you can hover over issue numbers in the Activity feed for GitHub integration, but when a comment is posted to an issue/PR, the content is unavailable. It would be pretty nice if it showed the comment (as a hovertext like the main body of the issue, or just inline).

My team currently is looking to stop using Slack but its ability to show comment text in the channel is something that we've come to rely on a surprising amount.

**Comment by MadLittleMods** [comment] 2015-08-22 18:18
Exact duplicate of gitterHQ/gitter#635 from same author.

**Closed by MadLittleMods** 2015-08-22 18:18 UTC
Labels: enhancement
