### ISSUE TITLE
Github integration does not work correctly ?

### ISSUE THREAD

**Issue by andersevenrud** [gitterHQ/gitter#1597] opened 2017-01-28 21:21 UTC
Hi,

I was trying to add a Github integration (because the existing one is really old), and I'm getting some strange behavior:

1. Clicked the icon in Gitter interface
2. Clicked `Integrations`
3. Clicked `Github` (Illustration 1)
4. The modal was filled with the Github gitter page (Illustration 2)
5. My integration list was now filled with something that I don't know what is (Illustration 3)

Oh, and also the feed does not seem to be working since the downtime this week.

#### Illustration 1
![gitter-01](https://cloud.githubusercontent.com/assets/161548/22399911/c03011c4-e5a7-11e6-90ed-b62e42de373d.png)

#### Illustration 2
![gitter-02](https://cloud.githubusercontent.com/assets/161548/22399912/c0334538-e5a7-11e6-87a0-fd72a4e15322.png)

#### Illustration 3
![gitter-03](https://cloud.githubusercontent.com/assets/161548/22399913/c0344f0a-e5a7-11e6-8f14-f1b53b929c87.png)

**Comment by JoshEngebretson** [comment] 2017-01-29 00:33
Our feed is also broken since the downtime

**Comment by MadLittleMods** [comment] 2017-01-30 05:36
Duplicate of https://github.com/gitterHQ/gitter/issues/1596

**Closed by MadLittleMods** 2017-01-30 05:36 UTC
