### ISSUE TITLE
Searching and tapping on yourself creates an additional sidebar

### ISSUE THREAD

**Issue by johnpryan** [gitterHQ/gitter#1713] opened 2017-05-25 21:00 UTC
steps to reproduce:

1. search for your username
2. tap on your username
3. observe an additional sidebar appears next to the current one.

![screen shot 2017-05-25 at 2 00 26 pm](https://cloud.githubusercontent.com/assets/1145719/26470441/88b3ba96-4152-11e7-92a6-ab6d8782b6cd.png)

**Comment by MadLittleMods** [comment] 2017-05-25 21:15
Duplicate of https://github.com/gitterHQ/gitter/issues/1277

**Closed by MadLittleMods** 2017-05-25 21:15 UTC
