### ISSUE TITLE
Take and attach photos from within the Gitter app.

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1418] opened 2016-09-01 21:34 UTC
Pretty self explanatory. Add a camera button next to the text input box. A bit hard on android as you cheat and use the webview input box not a native one

**Comment by MadLittleMods** [comment] 2016-09-01 21:37
Duplicate of https://github.com/gitterHQ/gitter/issues/854

Please use the search on here before posting. It's ok if you miss it but this is the second duplicate posted.

**Closed by MadLittleMods** 2016-09-01 21:37 UTC
