### ISSUE TITLE
Chat input area autofocus on keypress

### ISSUE THREAD

**Issue by mydigitalself** [gitterHQ/gitter#311] opened 2014-07-08 10:20 UTC
from @cmr
>It would be nice if I started typing and the chatbox isn't focused, it focused it for me.

Need to consider how this works with valid shortcut keys (e.g. r/q to reply).

**Comment by MadLittleMods** [comment] 2015-08-26 23:04
Closing as a duplicate of gitterHQ/gitter#600. That issue has more details and ideas fleshed out out.

**Closed by MadLittleMods** 2015-08-26 23:04 UTC
Labels: bug, enhancement
