### ISSUE TITLE
Duplicate notifications on Gitter Desktop; toast + Gitter

### ISSUE THREAD

**Issue by LB--** [gitterHQ/gitter#1223] opened 2016-04-19 22:54 UTC
I'm using Windows 10 Pro 64bit and running Gitter Next v3.0.3 Desktop App

Whenever I get a notification, I get two - one which does not work from "Gitter" which has a blank square where the avatar should be, and another from "toast" that has the avatar and works properly when you click it.

Example of my Action Center when this happens:
![image](https://cloud.githubusercontent.com/assets/1296838/14658102/2f0aa338-0657-11e6-9ea1-23499e040ea7.png)

It's pretty annoying. When I first tried to report this I decided to uninstall and reinstall Gitter, and that seemed to fix the problem at first, but now it has come back and I am not sure why.

**Comment by MadLittleMods** [comment] 2016-04-20 02:22
Duplicate of https://github.com/gitterHQ/desktop/issues/130

**Closed by MadLittleMods** 2016-04-20 02:22 UTC
