### ISSUE TITLE
share copy button hover state is pink

### ISSUE THREAD

**Issue by samccone** [gitterHQ/gitter#523] opened 2015-01-16 03:43 UTC
![](http://dl.dropbox.com/u/36928599/Screenshots/0o~.png)

**Comment by samccone** [comment] 2015-01-16 03:43
:pig:

**Comment by waltfy** [comment] 2015-01-16 14:02
Thanks @samccone!

**Comment by waltfy** [comment] 2015-01-19 15:58
Hi @samccone, what browser were you using? Also, do you have Flash installed? We use [zeroclipboard](http://zeroclipboard.org/) which relies on Flash. :see_no_evil:

**Comment by samccone** [comment] 2015-01-19 16:06
This is in the embedded app, so safari I suppose (unless you guys switched to NWK .. then chromium) And yep I do have flash. :moneybag:

**Comment by waltfy** [comment] 2015-01-20 11:07
We are in the process of switching to `NW.js` (former `NWK`) soon, so I'll see if I can reproduce this issue there.

**Comment by mydigitalself** [comment] 2015-01-23 14:31
Sam we can't reproduce this and we're switching over to NWK, so we'll just close this yo.

**Closed** 2015-01-23 14:31 UTC
Labels: pebble

**Comment by samccone** [comment] 2015-01-23 14:56
kk :+1:
