### ISSUE TITLE
Add user setting "Never expand links"?

### ISSUE THREAD

**Issue by terakilobyte** [gitterHQ/gitter#1354] opened 2016-07-26 05:12 UTC
I did a brief search but didn't find anything under "expand".

Please add a user option to "never expand links".

It would also be nice if there was an option to collapse code and image embeds by default. In very busy rooms a big image, code paste, or a few codepen links can quickly page the chat.

**Comment by MadLittleMods** [comment] 2016-07-26 06:35
Duplicate of https://github.com/gitterHQ/gitter/issues/714

**Closed by MadLittleMods** 2016-07-26 06:35 UTC
