### ISSUE TITLE
`javascript:` protocol easter egg broken link

### ISSUE THREAD

**Issue by Arinerron** [gitterHQ/gitter#1242] opened 2016-05-03 23:04 UTC
This is a somewhat silly feature I am reporting, but regardless:

When you sent the message `[click me](javascript:rickRoll()` (yes, I know the missing `)` at the end) (or any JS works), it finds the JavaScript and replaces it with the rickroll video: https://www.youtube.com/watch?v=BROWqjuTM0g
However, the video was taken down, so it should instead send you to a working one like: https://www.youtube.com/watch?v=dQw4w9WgXcQ (which is a working version).

**Comment by MadLittleMods** [comment] 2016-05-03 23:34
Duplicate of https://github.com/gitterHQ/gitter/issues/1148

**Comment by Arinerron** [comment] 2016-05-04 00:44
@MadLittleMods This is on a different platform though, this isn't next Gitter.

**Comment by MadLittleMods** [comment] 2016-05-04 04:25
@Arinerron ahhh, that is some markdown for a chat message.

Looks like that code is here https://github.com/gitterHQ/gitter-markdown-processor/blob/3483cd0de6661d436df448b1d4df27afbb6252e0/lib/process-chat.js#L113 - Can you create an issue over there as well?

Feel free to submit a PR if you are up for it.

**Comment by Arinerron** [comment] 2016-05-04 05:31
@MadLittleMods Thanks! Tip: Here's the URL's click stats: http://goo.gl/a7HIYr+ :stuck_out_tongue_winking_eye:

**Closed** 2016-05-04 12:14 UTC
Labels: bug
