### ISSUE TITLE
Add option to sort search results in chronological order

### ISSUE THREAD

**Issue by ejsmith** [gitterHQ/gitter#669] opened 2015-04-17 16:13 UTC
It is really frustrating to not be able to sort the search results in chronological order.  Maybe we can have an option to sort by relevance and also by date. I also think that the age of the messages should be taken into account for the relevance ranking.

**Comment by MadLittleMods** [comment] 2015-09-15 11:12
Duplicate of #566. Move discussion there.

**Closed by MadLittleMods** 2015-09-15 11:12 UTC
Labels: feature
