### ISSUE TITLE
Left menu doubles when opening chat with myself

### ISSUE THREAD

**Issue by av-elier** [gitterHQ/gitter#1645] opened 2017-03-28 18:20 UTC
How to reproduce:
- search your nickname,
- click on you in search results,
- left menu doubles.

Desktop app v3.1.0. on windows 10. "Next" also have this bug. Web version haven't.

![2017-03-28_21-10-30](https://cloud.githubusercontent.com/assets/3632999/24420478/ab8b8924-13fb-11e7-8854-d441a5944f94.png)

**Comment by MadLittleMods** [comment] 2017-03-28 18:46
Duplicate of https://github.com/gitterHQ/gitter/issues/1277

**Closed by MadLittleMods** 2017-03-28 18:46 UTC
