### ISSUE TITLE
"Mute users" feature

### ISSUE THREAD

**Issue by AkiraLaine** [gitterHQ/gitter#1388] opened 2016-08-23 08:25 UTC
Hey Gitter!

Time and again, people get messaged by other users who either harass, spam or just troll. Gitter doesn't currently have a "mute user" button, or some sort of way to ban the user from messaging you.

Is this something you guys are looking to have? It would be cool if this feature was implemented.

**Comment by MadLittleMods** [comment] 2016-08-23 10:03
Hey @AkiraLaine,

You can set the notification settings for that room to `Mute` but the room will still appear again if you hide it.

Feel free to report any harassment and we will take care of the trouble user. support@gitter.im

Duplicate of https://github.com/gitterHQ/gitter/issues/245

**Closed by MadLittleMods** 2016-08-23 10:03 UTC
