### ISSUE TITLE
Twitter Authorization does not work

### ISSUE THREAD

**Issue by aparentMMS** [gitterHQ/gitter#1250] opened 2016-05-11 17:14 UTC
Firefox (latest)
Mac OSX 10.8
Logged into Twitter
in private room, 
Select Authorize via Twitter, it jumps to twitter and says authorizing... and sits there forever.

**Comment by MadLittleMods** [comment] 2016-05-11 19:18
Works just fine for me on the latest Firefox v46.0.1 on OSX 10.11.4 or Windows 10.

**Comment by aparentMMS** [comment] 2016-05-11 20:42
Tried another computer, firefox  46, mac OSX 10.10.5. 
https://gitter.im/homehomepage, I click "Sign in to start talking" select twitter, and then right side of homepage goes blank.  

disabled adblocker, tried again. same blank frame. 

do you need to enable popups? you shouldn't need to, or it should tell you if so.

**Comment by MadLittleMods** [comment] 2016-05-11 20:47
@aparentMMS It should just redirect you to the Twitter authorization page or the Twitter sign-page. Can you try with no extensions in a incognito instance to eliminate all of those variables?

**Comment by aparentMMS** [comment] 2016-05-11 21:08
I tried a private window where it seemed to allow authorization. I've since de-authorized from twitter settings, however, and it's not saying anything about that in the private window...

**Comment by mydigitalself** [comment] 2016-05-16 09:35
I can't reproduce this either. Is there anything in your JavaScript console that indicates an error?

**Comment by mydigitalself** [comment] 2016-05-31 08:32
Closing as we can't reproduce and had no other reports.

**Closed by mydigitalself** 2016-05-31 08:32 UTC
