### ISSUE TITLE
Searching myself bug

### ISSUE THREAD

**Issue by KeyWeeUsr** [gitterHQ/gitter#1349] opened 2016-07-21 09:53 UTC
When I go `Search Gitter` → `<my username>` and select myself in the `Rooms & People`, I end up with this behavior. Strongly reminds me old websites based on `iframe`.

<img src="https://cloud.githubusercontent.com/assets/8825439/17018555/8edfc8c2-4f38-11e6-81e7-0cb529429f12.png" />

**Comment by MadLittleMods** [comment] 2016-07-21 09:58
Duplicate of https://github.com/gitterHQ/gitter/issues/1277

**Closed by MadLittleMods** 2016-07-21 09:58 UTC
