### ISSUE TITLE
Broken video (very small bug)

### ISSUE THREAD

**Issue by VMBindraban** [gitterHQ/gitter#1195] opened 2016-03-31 08:28 UTC
De url in de footer of http://next.gitter.im/ is broken.
Referring to:

>You know what to do with it. If not, go here.

**Comment by MadLittleMods** [comment] 2016-03-31 10:41
Duplicate of https://github.com/gitterHQ/gitter/issues/1148

**Closed by MadLittleMods** 2016-03-31 10:41 UTC
