### ISSUE TITLE
EXC_BAD_ACCESS (SIGSEGV) crash on OSX 10.8.5

### ISSUE THREAD

**Issue by izzaboo** [gitterHQ/gitter#1267] opened 2016-05-25 21:33 UTC
Crash log: https://gist.github.com/izzaboo/589b6cc26253a4655123ef2b87bf2b48

Gitter works in updated Safari.

The Gitter app starts up, but when drawing content the app window; after avatars are drawn but before any text, it unexpectedly quits.

I can reopen the app, choose to not reopen windows from crash recovery dialog, and have access to the menu bar utility of the app. But if I try to open a window from a menu bar option the same crash happens.

Edit to add: When logged out of gitter in app, the Sign In window opens w/o issue.

**Comment by izzaboo** [comment] 2016-05-25 21:46
I can reopen the app, choose to not reopen windows, and have access to the menu bar utility of the app. But if I try to open a window the same crash happens.

**Comment by MadLittleMods** [comment] 2016-05-25 21:46
Other reports of crashes on OSX with `EXC_BAD_ACCESS (SIGSEGV)` here:

 - :point_up: [May 13, 2016 3:29 PM](https://gitter.im/gitterHQ/gitter?at=57363924c61823687d3bb41b)
    - Crash report: https://gist.github.com/izzaboo/589b6cc26253a4655123ef2b87bf2b48
 - https://gitter.zendesk.com/agent/tickets/2259
    - Crash report: https://gist.github.com/anonymous/f5fcb4bb9d3e72165e42da86a80c1a5f

**Comment by MadLittleMods** [comment] 2016-05-26 01:03
Sorry, remembering back this is a duplicate of https://github.com/gitterHQ/desktop/issues/146 and I have re-opened that issue.

**Closed by MadLittleMods** 2016-05-26 01:03 UTC
Labels: bug, desktop, mac
