### ISSUE TITLE
Twitter Integration

### ISSUE THREAD

**Issue by tomspilman** [gitterHQ/gitter#1291] opened 2016-06-13 20:05 UTC
It would be nice to have support for tweets from our project's Twitter account to appear as activity in our Gitter room.  This ensures developers in the Gitter room see announcements about the project as they happen.

Seems like something that could be done with an "integration" plugin.

**Comment by MadLittleMods** [comment] 2016-06-13 20:07
Duplicate of https://github.com/gitterHQ/services/issues/18

**Closed by MadLittleMods** 2016-06-13 20:07 UTC
