### ISSUE TITLE
Add ability to remove other's comments for admin

### ISSUE THREAD

**Issue by k-bx** [gitterHQ/gitter#918] opened 2015-10-17 09:17 UTC
Hi!

There had been inappropriate content (threat and abuse) in one of rooms I created, and I'd like to remove that content. But, even when logged in as a room creator, I can't do that.

Can you implement such a feature please? Thank you.

**Comment by MadLittleMods** [comment] 2015-10-18 19:31
Duplicate of https://github.com/gitterHQ/gitter/issues/620

**Closed by MadLittleMods** 2015-10-18 19:31 UTC
