### ISSUE TITLE
Copy/Paste of usernames

### ISSUE THREAD

**Issue by jasongrout** [gitterHQ/gitter#1609] opened 2017-02-14 13:52 UTC
On OS X Chrome 56, when I select a username in the chat above a message and try to copy it using Cmd-C, it seems to copy the message, not the username.

**Comment by MadLittleMods** [comment] 2017-02-21 03:34
:+1: You actually do copy the username. You can see this if you paste somewhere other than the Gitter chat input.

But when pasting into the Gitter chat input, something copied from a message gets interpolated to the markdown of the message.

**Comment by MadLittleMods** [comment] 2017-02-21 03:34
Duplicate of https://github.com/gitterHQ/gitter/issues/1048

**Closed by MadLittleMods** 2017-02-21 03:34 UTC
Labels: bug
