### ISSUE TITLE
[Mobile] Github activity intermittently displaces main chat window

### ISSUE THREAD

**Issue by ProbonoBonobo** [gitterHQ/gitter#1391] opened 2016-08-24 14:38 UTC
Site mostly works great on mobile, but the right column sometimes juts way out and dominates >50% of the width of the screen. Most of the time it's fine! Looks normal way more often than it doesn't. For what it's worth, the right column issue seems to happen more often when going from homepage->room than when pointing browser directly to a room.

![image](https://cloud.githubusercontent.com/assets/4884737/17933946/e074a5a2-69ca-11e6-8636-37064c608c9d.png)
![image](https://cloud.githubusercontent.com/assets/4884737/17933947/e09c337e-69ca-11e6-868d-6e66a126b307.png)

**Comment by MadLittleMods** [comment] 2016-08-25 06:47
Duplicate of https://github.com/gitterHQ/gitter/issues/1263

When on home, explore moving to a room, we incorreclty show the desktop site. On refresh, you will get the correct UI.

**Closed by MadLittleMods** 2016-08-25 06:47 UTC
Labels: mobile
