### ISSUE TITLE
[0] and [1] get converted to some GitHub repo links.

### ISSUE THREAD

**Issue by SebastianNiemann** [gitterHQ/gitter#1443] opened 2016-09-16 10:09 UTC
I am not really sure if this is erroneous/undesired behaviour (it was at least unexpected for me) and where this comes from, but when I write

```
[0] some text
[1] some other text
[2] some other text again
```

This gets converted into

> **[0](https://github.com/thejohnhoffer/viaWebGL/blob/master/demo/pac/main.js)** some text
> **[1](https://github.com/jaspervdj/websockets/blob/master/example/server.lhs)** some other text
> [2] some other text again

on Gitter.

**Comment by MadLittleMods** [comment] 2016-09-16 10:10
Duplicate of https://github.com/gitterHQ/gitter/issues/1041

**Closed by MadLittleMods** 2016-09-16 10:10 UTC
