### ISSUE TITLE
Use URL schemes for the apps.

### ISSUE THREAD

**Issue by TheDiamondYT1** [gitterHQ/gitter#1417] opened 2016-09-01 19:28 UTC
So when on the mobile site it will display a banner somewhere saying "Open in app" and you can dismiss it if you dont want.

This can be implemented in Android and iOS apps.

[Tutorial](http://fokkezb.nl/2013/09/20/url-schemes-for-ios-and-android-2/)

**Comment by MadLittleMods** [comment] 2016-09-01 19:29
Duplicate of https://github.com/gitterHQ/gitter/issues/904

**Comment by TheDiamondYT1** [comment] 2016-09-01 19:30
Oh sorry github should add a mobile site search :p

**Closed by MadLittleMods** 2016-09-01 19:29 UTC
