### ISSUE TITLE
People amount on organization page is wrong

### ISSUE THREAD

**Issue by xSAVIKx** [gitterHQ/gitter#1523] opened 2016-11-17 15:50 UTC
On organization page there is following info:
* rooms amount
* people amount

And right now people amount just sums up people from each room, but for sure it's not right action to do.
From my point of view, people amount should show how many unique users are currently in all rooms, but now it shows just sum of each room users amount.
Take look at right corner (3 rooms, 24 people, but really there are now only 9 unique users in all rooms):
![screenshot from 2016-11-17 17-48-58](https://cloud.githubusercontent.com/assets/5675689/20396210/220aea7e-acee-11e6-8bba-2154e053ed22.png)

**Comment by MadLittleMods** [comment] 2016-11-17 16:40
Duplicate of https://github.com/gitterHQ/gitter/issues/1075

**Closed by MadLittleMods** 2016-11-17 16:40 UTC
