### ISSUE TITLE
Able to edit deleted message by pressing up

### ISSUE THREAD

**Issue by jv110** [gitterHQ/gitter#1512] opened 2016-11-12 22:25 UTC
By editting a deleted message, it will display the new text and the buttons will be enabled, but will still be light gray like if it was deleted. Going to other conversation and back will "fix" the bug, making it normal-colored.

Image:
![image](https://cloud.githubusercontent.com/assets/7979845/20242459/611511de-a90d-11e6-8019-8931f3bc00fe.png)

Reproduction steps: send a message, delete it, press up, write new text and press enter.

(Note: since now deleting a message makes it disappear, you'll have to press edit and empty the box, which gives the old "This message was deleted")

**Comment by MadLittleMods** [comment] 2016-11-14 15:34
Duplicate of https://github.com/gitterHQ/gitter/issues/415

**Closed by MadLittleMods** 2016-11-14 15:34 UTC
