### ISSUE TITLE
Add information about person timezone

### ISSUE THREAD

**Issue by jkubrynski** [gitterHQ/gitter#1139] opened 2016-02-23 08:46 UTC
That information as well as something like office hours will make chats between continents much easier.

**Comment by MadLittleMods** [comment] 2016-02-23 09:28
Duplicate of

 - Provide user local time: https://github.com/gitterHQ/gitter/issues/1018
 - Show user joined date and idle time in a room: https://github.com/gitterHQ/gitter/issues/278

**Closed by MadLittleMods** 2016-02-23 09:28 UTC
