### ISSUE TITLE
Markdown Help menu "Link" points to removed YouTube video.

### ISSUE THREAD

**Issue by mdelgadonyc** [gitterHQ/gitter#1165] opened 2016-03-11 22:35 UTC
In the Markdown Help menu the word "Link" is itself a hyperlink that points to the YouTube video https://www.youtube.com/watch?v=BROWqjuTM0g but unfortunately the video is no longer available due alleged copyright infringement: "Rick Roll ..." This video is no longer available due to a copyright claim by Twentieth Century Fox Film Corp.

![broken-youtube-link-2016-03-11](https://cloud.githubusercontent.com/assets/17136771/13717448/92c2a298-e7af-11e5-8a4b-a656b8a6d6cb.jpg)

-Moisés Delgado

**Comment by MadLittleMods** [comment] 2016-03-11 23:29
Duplicate of https://github.com/gitterHQ/gitter/issues/1148

**Closed by MadLittleMods** 2016-03-11 23:29 UTC
