### ISSUE TITLE
Web app glitch

### ISSUE THREAD

**Issue by xiaopow** [gitterHQ/gitter#1423] opened 2016-09-06 12:51 UTC
If I search for my profile name and click on it. It will open another side menu.
![screen shot 2016-09-06 at 8 46 27 pm](https://cloud.githubusercontent.com/assets/10229915/18274140/9adaf592-7473-11e6-821c-3e96b2c6ee3e.png)

**Comment by MadLittleMods** [comment] 2016-09-06 13:00
Duplicate of https://github.com/gitterHQ/gitter/issues/1277

**Closed by MadLittleMods** 2016-09-06 13:00 UTC
