### ISSUE TITLE
Allow hyperlinking of irc:// URLs in chat

### ISSUE THREAD

**Issue by grahamperrin** [gitterHQ/gitter#1405] opened 2016-08-27 07:31 UTC
https://gitter.im/trueos/lumina?at=57c13ff43cdeb6467b75795f for example, initially I wrote – 

```
irc://chat.freenode.net/#lumina-desktop
```

– only _half_-expecting that to be recognised as a URL. It was not recognised, so I edited to: 

```
[irc://chat.freenode.net/#lumina-destop](irc://chat.freenode.net/#lumina-destop)
```

**Expected**

A link to 
```
irc://chat.freenode.net/#lumina-desktop
```

**Actual result**

A link to 
```
http://irc//chat.freenode.net/#lumina-destop
```

**Comment by MadLittleMods** [comment] 2016-08-28 01:16
Duplicate of https://github.com/gitterHQ/gitter/issues/667, applies to any protocol other than `http`/`https`.

**Closed by MadLittleMods** 2016-08-28 01:16 UTC
