### ISSUE TITLE
[OS X] Allow Gitter to run without a dock icon

### ISSUE THREAD

**Issue by ldionne** [gitterHQ/gitter#744] opened 2015-06-24 21:17 UTC
For small apps like this, it is nice to avoid cluttering one's dock by having only a menubar item, no dock item. We should be able to tweak this through a simple checkbox in the preferences.

This is a "duplicate" of gitterHQ/desktop#61; it seems like the right place to open issues is here, since the other issue did not get an answer.

**Comment by mydigitalself** [comment] 2015-06-26 09:27
Hi there,

One of the reasons we open sources the desktop app is to get assistance from our community with certain features. We are a small team and can't address everything ourselves as yet.

I'm going to close this issue as it is a duplicate of gitterHQ/desktop#61 and hope that the community can help give back a little.

**Closed by mydigitalself** 2015-06-26 09:27 UTC
